### ISSUE TITLE
Template loading

### ISSUE THREAD

**Issue by pizarrodiego** [django-blog-zinnia/zinnia-theme-html5#1]
I have completed all steps for the installation of zinnia and zinnia_html5.
I see no changes to the layout after registering zinnia_html5 (before zinnia) and activating the egg templates loader... the 'old' templates are still used. There are no errors either.

I use django 1.3

Thanks for your feedback,

Diego Pizarro

**Comment by Fantomas42** [comment]
Hi ,

no changes on the layout are provided for zinnia_html5, only the markups used.

What is the doctype of your generated page ?

**Comment by pizarrodiego** [comment]
Hello,

Thanks for your answer! I had not understood what the html5 templates implied.

My doctype is
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">

**Comment by Fantomas42** [comment]
Effectively you are not in HTML5.

Can you paste me your settings in private to take a look on the problem ?

**Comment by Fantomas42** [comment]
Closing until further details.
