### ISSUE TITLE
Superfluous endblock in _entry_detail_base.html

### ISSUE THREAD

**Issue by azaghal** [django-blog-zinnia/zinnia-theme-html5#2]
There's one superfluous {% endblock %} tag in the _entry_detail_base.html. I'm not too experienced with Django, so either it's necessary to remove the endblock at line 11 (based on indentation, it's probably this) or at line 43.

After removing the line 11 in the file the theme started working ok for me (Zinnia 0.12.1).

**Comment by Fantomas42** [comment]
Thanks for your vigilance !
