### ISSUE TITLE
Traceback on trying this theme

### ISSUE THREAD

**Issue by mcepl** [django-blog-zinnia/zinnia-theme-html5#3]
Hi, testing Zinnia on my localhost. Bootstrap theme works just fine (and looks useable), however this theme ends with traceback ... http://mcepl.fedorapeople.org/tmp/TemplateSyntaxError%20at%20_weblog_.html

Any thoughts what I do wrong?

(forgive me being complete Django and Zinnia newbie, so I could do something stupid).

**Comment by Fantomas42** [comment]
Hi,

please use the v0.13 of Zinnia, it should be OK after that.

The widont filter is available in this version of Zinnia.

**Comment by mcepl** [comment]
0.13 is what I have (yesterday downloaded via pip install)

**Comment by Fantomas42** [comment]
Are you sure that the v0.13 is currently used in your installation and not a previous version ?

**Comment by mcepl** [comment]
I have never installed previous version.

**Comment by Fantomas42** [comment]
You have installed the v0.13 from Pypi ?

**Comment by mcepl** [comment]
yes

```
pip install --user zinnia-theme-html5
```

**Comment by mcepl** [comment]
You are right ... see https://github.com/Fantomas42/django-blog-zinnia/issues/305#issuecomment-30804626 ... I had 0.12.1.
