### ISSUE TITLE
what django_zinnia version?

### ISSUE THREAD

**Issue by guocdfeifei** [django-blog-zinnia/zinnia-theme-html5#4]
version 1.3 err
raise e
NoReverseMatch: Reverse for 'entry_archive_index' with arguments '()' and keyword arguments '{}' not found.

**Comment by Fantomas42** [comment]
If you use Zinnia 0.13, try the version 0.3.2 of the theme.
If your version of Zinnia used is more recent, use the version 0.4 of the theme.

Regards

**Comment by guocdfeifei** [comment]
thanks
